### ISSUE TITLE
Image Seeds

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/Rohit#5]
#### As a developer I want at least 20 images to be created when I setup the database.

Acceptance criteria:
- [x] After running `rake db:setup` at least 20 images are shown in the
  homepage.
- [x] When a new app is deployed on heroku (e.g., every review app), that app
  has at least 20 images on its homepage.

Dependencies:
- Image Index

**Comment by Rohit-L** [comment]
I am closing this issue because my mentor is not available for the next couple days and I need the seed file to work on the rest of the project.
